SELECT 
id_eteko AS id,
created_at AS date_creation,
statut,
categorie_produit,
designation_franchise,
description_franchiseur,
designation_courte,
designation_longue,
designation_longue_personnalisee,
reference_interne,
code_produit,
type,
prix_d_achat,
prix_de_vente_ht,
unite_de_vente,
prix_d_achat_fournisseur_ht,
prix_de_vente_conseille_ht,
prix_d_achat_franchise_ht,
taux_tva,
fournisseurs,
commentaire,
id_id_produit_franchiseur AS id_produit_franchiseur,
id_groupe_franchise AS id_franchise,
groupe_franchise AS franchise,
categorie_cooperative,
compte_comptable_produit_franchiseur,
compte_comptable_produit_franchise
FROM BI_produit