SELECT
id_eteko AS id,
code_client AS codeclient,
siret_ AS siret,
statut_client AS statut,
prenom_pardefaut AS prenom,
nom_pardefaut AS nom,
commentaire,
type,
denomination_societe AS societe,
civilite_pardefaut AS civilite,
email_par_defaut AS email,
id_user AS attribue_a,
adresse,
complement_d_adresse AS complement_adresse,
codepostal,
ville,
pays,
latitude,
longitude,
mobile,
telephone,
lead_franchiseur AS lead_franchiseur,
origine_du_client,
created_date AS date_de_creation,
cree_par,
n__tva_intracommunautaire AS tva_intracommunautaire,
compte_comptable_client
FROM BI_client