SELECT
id_eteko AS id,
n__commande AS numero,
statut,
complement,
titre,
date_de_la_commande,
id_client,
client,
id_id_user AS id_attribue_a,
id_user AS attribue_a,
commentaire,
total_ht,
total_tva,
total_ttc,
delai_reglement,
mode_reglement,
id_devis,
devis,
lieu_intervention,
adresse_facturation,
remise_ht,
remise_ttc,
total_tva_remise,
total_remise__ht AS total_remise_ht,
total_remise_ttc,
adresse,
complement_d_adresse,
code_postal,
ville,
avancement_facturation,
duree_estimee,
duree,
nombre_d_intervenants,
date_d_intervention,
type_remise_global,
remise_global,
cooperative
FROM BI_commande