SELECT 
id_eteko AS id,
id_client,
clientlie AS client,
email_client,
titre,
mentions,
complement,
id_opportunite,
opportunite,
note_autres,
date_du_devis,
date_envoi_devis,
date_signature_devis,
commentaire,
statuts AS statut,
total_ht,
total_tva,
total_ttc,
remise_ht,
remise_ttc,
total_remise_ttc,
total_remise_ht,
total_tva_remise,
id_id_user AS id_attribue_a,
id_user AS attribue_a,
delai_reglement,
mode_de_reglement,
lien_devis_ext,
adresse_du_vendeur,
lieu_intervention,
adresse_facturation_,
condition_de_paiement,
expiration,
date_changement_statut,
n__commande,
titre_opportunite,
statut_opportunite,
date_de_creation_opportunite,
type_intervention_opportunite,
type_de_client,
id_cooperative,
cooperative,
raison_du_refus,
duree_estimee,
devis_direct,
type_de_remise_globale__ AS type_remise_global,
montant_remise_globale___ AS remise_global
FROM BI_devis