SELECT
id_eteko AS id,
n__facture AS numero,
titre,
date_facture AS date_creation,
facture___avoir AS type,
statut_de_reglement,
id_groupe_franchise,
groupe_franchise,
adresse,
complement_d_adresse,
code_postal,
ville,
id_id_user AS id_attribue_a,
id_user AS attribue_a,
pays,
id_n__devis AS id_devis,
n__devis AS devis,
date_envoi_facture,
id_n__commande AS id_commande,
n__commande AS numero_commande,
date_echeance,
date_relance,
soldee,
type_partiel,
reste_a_regler,
total_facture_remise_ht,
total_facture_remise_ttc,
total_facture_remise_tva,
type_remise_global,
remise_global,
cooperative,
montant_regle_ttc,
notes_internes,
mode_reglement,
delai_reglement,
lieu_intervention,
etat,
id_client,
client_nom AS client,
total_ht,
total_ttc,
total_tva,
prefixe,
adresse_facturation,
date_demandee
FROM BI_facture