SELECT
actif,
id_lig AS id,
id_eteko AS id_devis,
prix_u_ht_lie,
total_tva,
montant_ttc_remise,
total_ht_remise,
total_tva_remise,
description,
description_courte_lie,
id_produit,
produit,
type_remise,
remise_ht,
total_ttc_remise,
prix_u_ht,
quantite,
categorie,
total_ht,
taux_tva_lie,
taux_tva,
total_ttc
FROM BI_devis_lignes_de_devis